title: Devporta Docs
description: Devporta API documentation.
ga: UA-145751066-1
serviceWorker: 
    updatePopup: true
# locales:
head:
    - link:
        - rel: icon
          href: /images/favicon.png
markdown:
    lineNumbers: true
themeConfig:
    repo: devporta/docs
    navbar: true
    lastUpdated: true
    logo: /images/logo.png
    sidebar: 
        - /
        - /sdk
    nav:
        - text: Language
          items: 
            - text: English
              link: /
            - text: French
              link: /fr/
        - text: Home
          link: https://devporta.com
