title: Devporta Docs
description: Devporta API documentation.
ga: UA-145751066-1
serviceWorker: true
head:
    - link:
        - rel: icon
          href: /images/favicon.png
markdown:
    lineNumbers: true
plugins:
    demo-code: true
    redirect: 
        locales: true
themeConfig:
    repo: devporta/docs
    logo: /images/logo.png
    navbar: true
    lastUpdated: true
    editLinks: true
    serviceWorker: 
        updatePopup: true
    sidebar: 
        - /
    nav:
        - text: Language
          items: 
            - text: English
              link: /
            - text: French
              link: /fr/
        - text: Console
          link: https://console.devporta.com
